-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 19, 2021 at 10:25 AM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.3.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bookpi`
--

-- --------------------------------------------------------

--
-- Table structure for table `book`
--

CREATE TABLE `book` (
  `isbn` varchar(17) NOT NULL,
  `title` varchar(100) NOT NULL,
  `author` varchar(20) NOT NULL,
  `publisher` varchar(20) NOT NULL,
  `year` int(11) NOT NULL,
  `weight` int(11) NOT NULL,
  `lang` varchar(10) NOT NULL,
  `category` varchar(20) NOT NULL,
  `description` text NOT NULL,
  `price` int(11) NOT NULL,
  `stock` int(11) NOT NULL,
  `image` blob NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `book`
--

INSERT INTO `book` (`isbn`, `title`, `author`, `publisher`, `year`, `weight`, `lang`, `category`, `description`, `price`, `stock`, `image`) VALUES
('978-1975399368', 'Weathering With You', 'Makoto Shinkai', 'Yen On', 2019, 300, 'English', 'Novel', 'Longing to escape his island home, a boy named Hodaka runs away during his first summer of high school to find a new life in Tokyo. As rain falls for days on end and Hodaka struggles to adjust, he meets a girl named Hina who holds a mysterious power: With a single prayer, she can part the clouds and bring back the sun. But her power comes at a price, and as the weather spirals further and further out of control, they must choose what future they truly want for themselves.\r\nWritten concurrently with production of the 2019 film Weathering With You, this novel comes straight from director Makoto Shinkai, the mind behind 2016\'s hit your name.!', 225000, 39, 0x3937382d313937353339393336382e6a7067),
('978-0316471862', 'your name.', 'Makoto Shinkai', 'Yen Press', 2017, 250, 'English', 'Novel', 'Mitsuha, a high school girl living in a rural town deep in the mountains, has a dream that she is a boy living an unfamiliar life in Tokyo. Taki, a high school boy living in Tokyo, dreams that he is a girl living in the mountains. As they realize they are changing places, their encounter sets the cogs of fate into motion. Written by director Makoto Shinkai, the work has become a global phenomenon!', 225000, 44, 0x3937382d303331363437313836322e6a7067),
('978-4048661690', 'Three Days of Happiness', 'Sugaru Miaki', 'Kadokawa', 2013, 158, 'English', 'Novel', 'Three Days of Happiness tells that: it seems nothing good will happen in my future life. As a result, the rest of my life is \'appraised\' with a price of ten thousand yen a year. I\'m so pessimistic for my future that I sell most of my rest life, thinking that at least I will live a happier life. However, things always go contrary to my wishes no matter what I do. As I repeatedly make the futile struggle, the \'monitor\' Miyagi appears. Unfortunately, I only have two months to live when I finally realize that living for Miyagi is the happiest thing.', 255000, 38, 0x3937382d343034383636313639302e6a7067),
('978-0553380163', 'A Brief History of Time', 'Stephen Hawking', 'Bantam', 1998, 317, 'English', 'Science', 'A landmark volume in science writing by one of the great minds of our time, Stephen Hawking’s book explores such profound questions as: How did the universe begin—and what made its start possible? Does time always flow forward? Is the universe unending—or are there boundaries? Are there other dimensions in space? What will happen when it all ends?\r\n\r\nTold in language we all can understand, A Brief History of Time plunges into the exotic realms of black holes and quarks, of antimatter and “arrows of time,” of the big bang and a bigger God—where the possibilities are wondrous and unexpected. With exciting images and profound imagination, Stephen Hawking brings us closer to the ultimate secrets at the very heart of creation.', 180000, 29, 0x3937382d303535333338303136332e6a7067),
('978-1524731670', 'Until the End of Time', 'Brian Greene', 'Knopf', 2020, 725, 'English', 'Science', 'Until the End of Time is Brian Greene\'s breathtaking new exploration of the cosmos and our quest to find meaning in the face of this vast expanse. Greene takes us on a journey from the big bang to the end of time, exploring how lasting structures formed, how life and mind emerged, and how we grapple with our existence through narrative, myth, religion, creative expression, science, the quest for truth, and a deep longing for the eternal. From particles to planets, consciousness to creativity, matter to meaning—Brian Greene allows us all to grasp and appreciate our fleeting but utterly exquisite moment in the cosmos.', 165000, 40, 0x3937382d313532343733313637302e6a7067),
('978-0316412001', 'Rivers of Power', 'Laurence C. Smith', 'Little, Brown Spark ', 2020, 635, 'English', 'Science', 'Rivers, more than any road, technology, or political leader, have shaped the course of human civilization. They have opened frontiers, founded cities, settled borders, and fed billions. They promote life, forge peace, grant power, and can capriciously destroy everything in their path. Even today, rivers remain a powerful global force -- one that is more critical than ever to our future.\r\n\r\nIn Rivers of Power, geographer Laurence C. Smith explores the timeless yet underappreciated relationship between rivers and civilization as we know it. Rivers are of course important in many practical ways (water supply, transportation, sanitation, etc). But the full breadth of their influence on the way we live is less obvious. Rivers define and transcend international borders, forcing cooperation between nations. Huge volumes of river water are used to produce energy, raw commodities, and food. Wars, politics, and demography are transformed by their devastating floods. The territorial claims of nations, their cultural and economic ties to each other, and the migrations and histories of their peoples trace back to rivers, river valleys, and the topographic divides they carve upon the world. And as climate change, technology, and cities transform our relationship with nature, new opportunities are arising to protect the waters that sustain us.\r\n\r\nBeautifully told and expansive in scope, Rivers of Power reveals how and why rivers have so profoundly influenced our civilization and examines the importance this vast, arterial power holds for the future of humanity.', 285000, 17, 0x3937382d303331363431323030312e6a7067),
('978-1541646858', 'The Idea of the Brain', 'Matthew Cobb', 'Basic Books', 2020, 680, 'English', 'Science', 'For thousands of years, thinkers and scientists have tried to understand what the brain does. Yet, despite the astonishing discoveries of science, we still have only the vaguest idea of how the brain works. In The Idea of the Brain, scientist and historian Matthew Cobb traces how our conception of the brain has evolved over the centuries. Although it might seem to be a story of ever-increasing knowledge of biology, Cobb shows how our ideas about the brain have been shaped by each era\'s most significant technologies. Today we might think the brain is like a supercomputer. In the past, it has been compared to a telegraph, a telephone exchange, or some kind of hydraulic system. What will we think the brain is like tomorrow, when new technology arises? The result is an essential read for anyone interested in the complex processes that drive science and the forces that have shaped our marvelous brains.', 420000, 10, 0x3937382d313534313634363835382e6a7067),
('978-1538744017', 'Human Diversity', 'Charles Murray', 'Twelve', 2020, 680, 'English', 'Science', 'The thesis of Human Diversity is that advances in genetics and neuroscience are overthrowing an intellectual orthodoxy that has ruled the social sciences for decades. The core of the orthodoxy consists of three dogmas:\r\n\r\n- Gender is a social construct.\r\n\r\n- Race is a social construct.\r\n\r\n- Class is a function of privilege.\r\n\r\nThe problem is that all three dogmas are half-truths. They have stifled progress in understanding the rich texture that biology adds to our understanding of the social, political, and economic worlds we live in.\r\n\r\nIt is not a story to be feared. \"There are no monsters in the closet,\" Murray writes, \"no dread doors we must fear opening.\" But it is a story that needs telling. Human Diversity does so without sensationalism, drawing on the most authoritative scientific findings, celebrating both our many differences and our common humanity.', 420000, 18, 0x3937382d313533383734343031372e706e67),
('978-1328879981', 'Infinite Powers', 'Steven Strogatz', 'Houghton Mifflin Har', 2019, 590, 'English', 'Science', 'Without calculus, we wouldn’t have cell phones, TV, GPS, or ultrasound. We wouldn’t have unraveled DNA or discovered Neptune or figured out how to put 5,000 songs in your pocket. \r\n \r\nThough many of us were scared away from this essential, engrossing subject in high school and college, Steven Strogatz’s brilliantly creative, down?to?earth history shows that calculus is not about complexity; it’s about simplicity. It harnesses an unreal number—infinity—to tackle real?world problems, breaking them down into easier ones and then reassembling the answers into solutions that feel miraculous. \r\n \r\nInfinite Powers recounts how calculus tantalized and thrilled its inventors, starting with its first glimmers in ancient Greece and bringing us right up to the discovery of gravitational waves (a phenomenon predicted by calculus). Strogatz reveals how this form of math rose to the challenges of each age: how to determine the area of a circle with only sand and a stick; how to explain why Mars goes “backwards” sometimes; how to make electricity with magnets; how to ensure your rocket doesn’t miss the moon; how to turn the tide in the fight against AIDS. \r\n \r\nAs Strogatz proves, calculus is truly the language of the universe. By unveiling the principles of that language, Infinite Powers makes us marvel at the world anew.', 285000, 20, 0x3937382d313332383837393938312e6a7067),
('978-0062338785', 'Bottle of Lies', 'Katherine Eban', 'Ecco', 2019, 725, 'English', 'Science', 'Many have hailed the widespread use of generic drugs as one of the most important public-health developments of the twenty-first century. Today, almost 90 percent of our pharmaceutical market is comprised of generics, the majority of which are manufactured overseas. We have been reassured by our doctors, our pharmacists and our regulators that generic drugs are identical to their brand-name counterparts, just less expensive. But is this really true?\r\n\r\nKatherine Eban’s Bottle of Lies exposes the deceit behind generic-drug manufacturing—and the attendant risks for global health. Drawing on exclusive accounts from whistleblowers and regulators, as well as thousands of pages of confidential FDA documents, Eban reveals an industry where fraud is rampant, companies routinely falsify data, and executives circumvent almost every principle of safe manufacturing to minimize cost and maximize profit, confident in their ability to fool inspectors. Meanwhile, patients unwittingly consume medicine with unpredictable and dangerous effects.\r\n\r\nThe story of generic drugs is truly global. It connects middle America to China, India, sub-Saharan Africa and Brazil, and represents the ultimate litmus test of globalization: what are the risks of moving drug manufacturing offshore, and are they worth the savings? \r\n\r\nA decade-long investigation with international sweep, high-stakes brinkmanship and big money at its core, Bottle of Lies reveals how the world’s greatest public-health innovation has become one of its most astonishing swindles', 270000, 28, 0x3937382d303036323333383738352e6a7067),
('978-0262043069', 'Extraterrestrial Languages', 'Daniel Oberhaus', 'The MIT Press', 2019, 430, 'English', 'Science', 'The endlessly fascinating question of whether we are alone in the universe has always been accompanied by another, more complicated one: if there is extraterrestrial life, how would we communicate with it? In this book, Daniel Oberhaus leads readers on a quest for extraterrestrial communication. Exploring Earthlings\' various attempts to reach out to non-Earthlings over the centuries, he poses some not entirely answerable questions: If we send a message into space, will extraterrestrial beings receive it? Will they understand? What languages will they (and we) speak? Is there not only a universal grammar (as Noam Chomsky has posited), but also a grammar of the universe?\r\n\r\nOberhaus describes, among other things, a late-nineteenth-century idea to communicate with Martians via Morse code and mirrors; the emergence in the twentieth century of SETI (the search for extraterrestrial intelligence), CETI (communication with extraterrestrial intelligence), and finally METI (messaging extraterrestrial intelligence); the one-way space voyage of Ella, an artificial intelligence agent that can play cards, tell fortunes, and recite poetry; and the launching of a theremin concert for aliens. He considers media used in attempts at extraterrestrial communication, from microwave systems to plaques on spacecrafts to formal logic, and discusses attempts to formulate a language for our message, including the Astraglossa and two generations of Lincos (lingua cosmica).\r\n\r\nThe chosen medium for interstellar communication reveals much about the technological sophistication of the civilization that sends it, Oberhaus observes, but even more interesting is the information embedded in the message itself. In Extraterrestrial Languages, he considers how philosophy, linguistics, mathematics, science, and art have informed the design or limited the effectiveness of our interstellar messaging.', 255000, 19, 0x3937382d303236323034333036392e6a7067),
('978-1250198280', 'Archaeology from Space', 'Sarah Parcak', 'Henry Holt and Co', 2019, 500, 'English', 'Science', 'National Geographic Explorer and TED Prize-winner Dr. Sarah Parcak gives readers a personal tour of the evolution, major discoveries, and future potential of the young field of satellite archaeology. From surprise advancements after the declassification of spy photography, to a new map of the mythical Egyptian city of Tanis, she shares her field’s biggest discoveries, revealing why space archaeology is not only exciting, but urgently essential to the preservation of the world’s ancient treasures.\r\n\r\nParcak has worked in twelve countries and four continents, using multispectral and high-resolution satellite imagery to identify thousands of previously unknown settlements, roads, fortresses, palaces, tombs, and even potential pyramids. From there, her stories take us back in time and across borders, into the day-to-day lives of ancient humans whose traits and genes we share. And she shows us that if we heed the lessons of the past, we can shape a vibrant future.', 225000, 24, 0x3937382d313235303139383238302e6a7067),
('978-1641291194', 'The Perfect World of Miwako Sumida', 'Clarissa Goenawan', 'Soho Press', 2020, 440, 'English', 'Novel', 'University sophomore Miwako Sumida has hanged herself, leaving those closest to her reeling. In the months before her suicide, she was hiding away in a remote mountainside village, but what, or whom, was she running from?\r\n\r\nRyusei, a fellow student at Waseda who harbored unrequited feelings for Miwako, begs her best friend Chie to bring him to the remote village where she spent her final days. While they are away, his older sister, Fumi, who took Miwako on as an apprentice in her art studio, receives an unexpected guest at her apartment in Tokyo, distracting her from her fear that Miwako’s death may ruin what is left of her brother’s life.\r\n\r\nExpanding on the beautifully crafted world of Rainbirds, Clarissa Goenawan gradually pierces through a young woman’s careful façade, unmasking her most painful secrets.', 255000, 42, 0x3937382d313634313239313139342e6a7067),
('978-0735213616', 'Breath: The New Science of a Lost Art', 'James Nestor', 'Riverhead Books', 2020, 500, 'English', 'Science', 'There is nothing more essential to our health and well-being than breathing: take air in, let it out, repeat 25,000 times a day. Yet, as a species, humans have lost the ability to breathe correctly, with grave consequences.\r\n\r\nJournalist James Nestor travels the world to figure out what went wrong and how to fix it. The answers aren’t found in pulmonology labs, as we might expect, but in the muddy digs of ancient burial sites, secret Soviet facilities, New Jersey choir schools, and the smoggy streets of São Paulo. Nestor tracks down men and women exploring the hidden science behind ancient breathing practices like Pranayama, Sudarshan Kriya, and Tummo and teams up with pulmonary tinkerers to scientifically test long-held beliefs about how we breathe.\r\n\r\nModern research is showing us that making even slight adjustments to the way we inhale and exhale can jump-start athletic performance; rejuvenate internal organs; halt snoring, asthma, and autoimmune disease; and even straighten scoliotic spines. None of this should be possible, and yet it is.\r\n\r\nDrawing on thousands of years of medical texts and recent cutting-edge studies in pulmonology, psychology, biochemistry, and human physiology, Breath turns the conventional wisdom of what we thought we knew about our most basic biological function on its head. You will never breathe the same again.', 420000, 23, 0x3937382d303733353231333631362e6a7067),
('978-0385351102', 'Weather: A novel', 'Jenny Offill', 'Knopf', 2020, 280, 'English', 'Novel', 'Lizzie Benson slid into her job as a librarian without a traditional degree. But this gives her a vantage point from which to practice her other calling: she is a fake shrink. For years she has tended to her God-haunted mother and her recovering addict brother. They have both stabilized for the moment, but Lizzie has little chance to spend her new free time with husband and son before her old mentor, Sylvia Liller, makes a proposal. Sylvia has become famous for her prescient podcast, Hell and High Water, and wants to hire Lizzie to answer the mail she receives: from left-wingers worried about climate change and right-wingers worried about the decline of western civilization.\r\n\r\nAs Lizzie dives into this polarized world, she begins to wonder what it means to keep tending your own garden once you\'ve seen the flames beyond its walls. When her brother becomes a father and Sylvia a recluse, Lizzie is forced to address the limits of her own experience—but still she tries to save everyone, using everything she\'s learned about empathy and despair, conscience and collusion, from her years of wandering the library stacks . . . And all the while the voices of the city keep floating in—funny, disturbing, and increasingly mad. ', 285000, 12, 0x3937382d303338353335313130322e6a7067),
('978-0805096606', 'The Mirror & the Light', 'Hilary Mantel', 'Henry Holt and Co', 2020, 860, 'English', 'Novel', 'With The Mirror & the Light, Hilary Mantel brings to a triumphant close the trilogy she began with her peerless, Booker Prize-winning novels, Wolf Hall and Bring Up the Bodies. She traces the final years of Thomas Cromwell, the boy from nowhere who climbs to the heights of power, offering a defining portrait of predator and prey, of a ferocious contest between present and past, between royal will and a common man’s vision: of a modern nation making itself through conflict, passion and courage.\r\n\r\nThe story begins in May 1536: Anne Boleyn is dead, decapitated in the space of a heartbeat by a hired French executioner. As her remains are bundled into oblivion, Cromwell breakfasts with the victors. The blacksmith’s son from Putney emerges from the spring’s bloodbath to continue his climb to power and wealth, while his formidable master, Henry VIII, settles to short-lived happiness with his third queen, Jane Seymour.\r\n\r\nCromwell, a man with only his wits to rely on, has no great family to back him, no private army. Despite rebellion at home, traitors plotting abroad and the threat of invasion testing Henry’s regime to the breaking point, Cromwell’s robust imagination sees a new country in the mirror of the future. All of England lies at his feet, ripe for innovation and religious reform. But as fortune’s wheel turns, Cromwell’s enemies are gathering in the shadows. The inevitable question remains: how long can anyone survive under Henry’s cruel and capricious gaze?\r\n\r\nEagerly awaited and eight years in the making, The Mirror & the Light completes Cromwell’s journey from self-made man to one of the most feared, influential figures of his time. Portrayed by Mantel with pathos and terrific energy, Cromwell is as complex as he is unforgettable: a politician and a fixer, a husband and a father, a man who both defied and defined his age.', 270000, 18, 0x3937382d303830353039363630362e6a7067),
('978-0062671189', 'The Night Watchman', 'Louise Erdrich', 'Harper', 2020, 635, 'English', 'Novel', 'Thomas Wazhashk is the night watchman at the jewel bearing plant, the first factory located near the Turtle Mountain Reservation in rural North Dakota. He is also a Chippewa Council member who is trying to understand the consequences of a new “emancipation” bill on its way to the floor of the United States Congress. It is 1953 and he and the other council members know the bill isn’t about freedom; Congress is fed up with Indians. The bill is a “termination” that threatens the rights of Native Americans to their land and their very identity. How can the government abandon treaties made in good faith with Native Americans “for as long as the grasses shall grow, and the rivers run”?\r\n\r\nSince graduating high school, Pixie Paranteau has insisted that everyone call her Patrice. Unlike most of the girls on the reservation, Patrice, the class valedictorian, has no desire to wear herself down with a husband and kids. She makes jewel bearings at the plant, a job that barely pays her enough to support her mother and brother. Patrice’s shameful alcoholic father returns home sporadically to terrorize his wife and children and bully her for money. But Patrice needs every penny to follow her beloved older sister, Vera, who moved to the big city of Minneapolis. Vera may have disappeared; she hasn’t been in touch in months, and is rumored to have had a baby. Determined to find Vera and her child, Patrice makes a fateful trip to Minnesota that introduces her to unexpected forms of exploitation and violence, and endangers her life.\r\n\r\nThomas and Patrice live in this impoverished reservation community along with young Chippewa boxer Wood Mountain and his mother Juggie Blue, her niece and Patrice’s best friend Valentine, and Stack Barnes, the white high school math teacher and boxing coach who is hopelessly in love with Patrice.\r\n\r\nIn the Night Watchman, Louise Erdrich creates a fictional world populated with memorable characters who are forced to grapple with the worst and best impulses of human nature. Illuminating the loves and lives, the desires and ambitions of these characters with compassion, wit, and intelligence, The Night Watchman is a majestic work of fiction from this revered cultural treasure.', 285000, 31, 0x3937382d303036323637313138392e6a7067),
('978-0765392107', 'The Future of Another Timeline', 'Annalee Newitz', 'Tor Books', 2019, 422, 'English', 'Novel', '1992: After a confrontation at a riot grrl concert, seventeen-year-old Beth finds herself in a car with her friend\'s abusive boyfriend dead in the backseat, agreeing to help her friends hide the body. This murder sets Beth and her friends on a path of escalating violence and vengeance as they realize many other young women in the world need protecting too.\r\n\r\n2022: Determined to use time travel to create a safer future, Tess has dedicated her life to visiting key moments in history and fighting for change. But rewriting the timeline isn’t as simple as editing one person or event. And just when Tess believes she\'s found a way to make an edit that actually sticks, she encounters a group of dangerous travelers bent on stopping her at any cost.\r\n\r\nTess and Beth’s lives intertwine as war breaks out across the timeline--a war that threatens to destroy time travel and leave only a small group of elites with the power to shape the past, present, and future. Against the vast and intricate forces of history and humanity, is it possible for a single person’s actions to echo throughout the timeline?', 255000, 30, 0x3937382d303736353339323130372e6a7067),
('978-1534402980', 'Ancestral Night', 'Elizabeth Bear', 'Gallery / Saga Press', 2019, 680, 'English', 'Novel', 'Halmey Dz and her partner Connla Kurucz are salvage operators, living just on the inside of the law...usually. Theirs is the perilous and marginal existence—with barely enough chance of striking it fantastically big—just once—to keep them coming back for more. They pilot their tiny ship into the scars left by unsuccessful White Transitions, searching for the relics of lost human and alien vessels. But when they make a shocking discovery about an alien species that has been long thought dead, it may be the thing that could tip the perilous peace mankind has found into full-out war.\r\n\r\nEnergetic and electrifying, Ancestral Night is a dazzling new space opera, sure to delight fans of Alastair Reynolds, Iain M. Banks, and Peter F. Hamilton.', 255000, 18, 0x3937382d313533343430323938302e6a7067),
('978-1101947883', 'Exhalation: Stories', 'Ted Chiang ', 'Knopf', 2019, 545, 'English', 'Novel', 'In these nine stunningly original, provocative, and poignant stories, Ted Chiang tackles some of humanity’s oldest questions along with new quandaries only he could imagine.\r\n\r\nIn “The Merchant and the Alchemist’s Gate,” a portal through time forces a fabric seller in ancient Baghdad to grapple with past mistakes and second chances. In “Exhalation,” an alien scientist makes a shocking discovery with ramifications that are literally universal. In “Anxiety Is the Dizziness of Freedom,” the ability to glimpse into alternate universes necessitates a radically new examination of the concepts of choice and free will.\r\n\r\nIncluding stories being published for the first time as well as some of his rare and classic uncollected work, Exhalation is Ted Chiang at his best: profound, sympathetic—revelatory.', 270000, 26, 0x3937382d313130313934373838332e6a7067),
('978-0761160960', 'Everything You Need to Ace Math', 'Workman Publishing', 'Workman Publishing C', 2016, 680, 'English', 'School', 'Everything You Need to Ace Math . . . covers everything to get a student over any math hump: fractions, decimals, and how to multiply and divide them; ratios, proportions, and percentages; geometry; statistics and probability; expressions and equations; and the coordinate plane and functions.\r\n\r\nThe BIG FAT NOTEBOOK™ series is built on a simple and irresistible conceit—borrowing the notes from the smartest kid in class. There are five books in all, and each is the only book you need for each main subject taught in middle school: Math, Science, American History, English Language Arts, and World History. Inside the reader will find every subject’s key concepts, easily digested and summarized: Critical ideas highlighted in neon colors. Definitions explained. Doodles that illuminate tricky concepts in marker. Mnemonics for memorable shortcuts. And quizzes to recap it all.\r\n\r\nThe BIG FAT NOTEBOOKS meet Common Core State Standards, Next Generation Science Standards, and state history standards, and are vetted by National and State Teacher of the Year Award–winning teachers. They make learning fun and are the perfect next step for every kid who grew up on Brain Quest.', 210000, 56, 0x3937382d303736313136303936302e6a7067),
('978-0471134473', 'Basic Physics: A Self-Teaching Guide', 'Karl F. Kuhn', 'J. Wiley', 1996, 545, 'English', 'School', 'fast, easy way to master the fundamentals of physics\r\n\r\nHere is the most practical, complete, and easy-to-use guideavailable for understanding physics and the physical world. Even ifyou don\'t consider yourself a \"science\" person, this book helpsmake learning key concepts a pleasure, not a chore. Whether youneed help in a course, want to review the basics for an exam, orsimply have always been curious about such physical phenomena asenergy, sound, electricity, light, and color, you\'ve come to theright place! This fully up-to-date edition of Basic Physics:\r\n* Has been tested, rewritten, and retested to ensure that you canteach yourself all about physics\r\n* Requires no math--mathematical treatments and applications areincluded in optional sections so that you can choose either amathematical or nonmathematical approach\r\n* Lets you work at your own pace with a helpful question-and-answerformat\r\n* Lists objectives for each chapter--you can skip ahead or findextra help if you need it\r\n* Reinforces what you learn with end-of-chapter self-tests', 240000, 20, 0x3937382d303437313133343437332e6a7067),
('978-3030151942', 'Principles of Mechanics', 'Salma Alrasheed', 'Springer', 2019, 680, 'English', 'School', 'This open access textbook takes the reader step-by-step through the concepts of mechanics in a clear and detailed manner. Mechanics is considered to be the core of physics, where a deep understanding of the concepts is essential in understanding all branches of physics. Many proofs and examples are included to help the reader grasp the fundamentals fully, paving the way to deal with more advanced topics. After solving all of the examples, the reader will have gained a solid foundation in mechanics and the skills to apply the concepts in a variety of situations.\r\n\r\nThe book is useful for undergraduate students majoring in physics and other science and engineering disciplines. It can also be used as a reference for more advanced levels.', 555000, 54, 0x3937382d333033303135313934322e6a7067),
('978-0134995540', 'University Calculus: Early Transcendentals', 'Joel R. Hass, Christ', 'Pearson', 2019, 2177, 'English', 'School', ' University Calculus: Early Transcendentals  helps students generalize and apply the key ideas of calculus through clear and precise explanations, thoughtfully chosen examples, meticulously crafted figures, and superior exercise sets. This text offers the right mix of basic, conceptual, and challenging exercises, along with meaningful applications. In the 4th Edition, new co-authors Chris Heil (Georgia Institute of Technology) and Przemyslaw Bogacki (Old Dominion University) partner with author Joel Hass to preserve the text’s time-tested features while revisiting every word, figure, and MyLab™ question with today’s students in mind. \r\n\r\n\r\nAlso available with MyLab Math \r\n\r\nBy combining trusted author content with digital tools and a flexible platform, MyLab Math personalizes the learning experience and improves results for each student. \r\n\r\n\r\nNote: You are purchasing a standalone product; MyLab Math does not come packaged with this content. Students, if interested in purchasing this title with MyLab Math, ask your instructor to confirm the correct package ISBN and Course ID. Instructors, contact your Pearson representative for more information. ', 1305000, 10, 0x3937382d303133343939353534302e6a7067),
('978-0134670959', 'Operating Systems: Internals and Design Principles', 'William Stallings', 'Pearson', 2017, 1133, 'English', 'School', ' Operating Systems: Internals and Design Principles provides a comprehensive, unified introduction to operating systems topics for readers studying computer science, computer engineering, and electrical engineering. Author William Stallings emphasizes both design issues and fundamental principles in contemporary systems, while providing readers with a solid understanding of the key structures and mechanisms of operating systems. He discusses design trade-offs and the practical decisions affecting design, performance and security. The text illustrates and reinforces design concepts, tying them to real-world design choices with case studies in Linux, UNIX, Android, and Windows 10.\r\n\r\n\r\nWith an unparalleled degree of support for project integration, plus comprehensive coverage of the latest trends and developments in operating systems, including cloud computing and the Internet of Things (IoT), the text provides everything readers need to keep pace with a complex and rapidly changing field. The 9th Edition has been extensively revised and contains new material, new projects, and updated chapters', 2400000, 12, 0x3937382d303133343637303935392e6a7067),
('978-1492043454', 'Fundamentals of Software Architecture: An Engineering Approach ', 'Mark Richards', 'O\'Reilly Media', 2020, 680, 'English', 'School', 'Salary surveys worldwide regularly place software architect in the top 10 best jobs, yet no real guide exists to help developers become architects. Until now. This book provides the first comprehensive overview of software architecture’s many aspects. Aspiring and existing architects alike will examine architectural characteristics, architectural patterns, component determination, diagramming and presenting architecture, evolutionary architecture, and many other topics.\r\n\r\nMark Richards and Neal Ford—hands-on practitioners who have taught software architecture classes professionally for years—focus on architecture principles that apply across all technology stacks. You’ll explore software architecture in a modern light, taking into account all the innovations of the past decade.', 660000, 20, 0x3937382d313439323034333435342e6a7067),
('978-0321552686', 'Documenting Software Architectures', 'Paul Clements', 'Addison-Wesley Profe', 2010, 950, 'English', 'School', 'Documenting Software Architectures, Second Edition, provides the most complete and current guidance, independent of language or notation, on how to capture an architecture in a commonly understandable form. Drawing on their extensive experience, the authors first help you decide what information to document, and then, with guidelines and examples (in various notations, including UML), show you how to express an architecture so that others can successfully build, use, and maintain a system from it. The book features rules for sound documentation, the goals and strategies of documentation, architectural views and styles, documentation for software interfaces and software behavior, and templates for capturing and organizing information to generate a coherent package.', 990000, 24, 0x3937382d303332313535323638362e6a7067),
('978-1292153964', 'Artificial Intelligence: A Modern Approach, Global Edition', 'Stuart Russell', 'Pearson', 2016, 1900, 'English', 'School', ' Artificial Intelligence: A Modern Approach, 3e offers the most comprehensive, up-to-date introduction to the theory and practice of artificial intelligence. Number one in its field, this textbook is ideal for one or two-semester, undergraduate or graduate-level courses in Artificial Intelligence.\r\n\r\nDr. Peter Norvig, contributing Artificial Intelligence author and Professor Sebastian Thrun, a Pearson author are offering a free online course at Stanford University on artificial intelligence.\r\n\r\n\r\nAccording to an article in The New York Times , the course on artificial intelligence is “one of three being offered experimentally by the Stanford computer science department to extend technology knowledge and skills beyond this elite campus to the entire world.” One of the other two courses, an introduction to database software, is being taught by Pearson author Dr. Jennifer Widom.\r\n\r\n\r\nArtificial Intelligence: A Modern Approach, 3e is available to purchase as an eText for your Kindle™, NOOK™, and the iPhone®/iPad®. ', 600000, 20, 0x3937382d313239323135333936342e6a7067);

-- --------------------------------------------------------

--
-- Table structure for table `bookorder`
--

CREATE TABLE `bookorder` (
  `idinvoice` varchar(15) NOT NULL,
  `isbn` varchar(17) NOT NULL,
  `qty` int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `bookorder`
--

INSERT INTO `bookorder` (`idinvoice`, `isbn`, `qty`) VALUES
('I0528124614', '978-0735213616', 1),
('I0528125725', '978-0735213616', 1),
('I0528125725', '978-1541646858', 2),
('I0528014744', '978-1975399368', 1),
('I0528035546', '978-0316471862', 1),
('I0602125709', '978-0735213616', 1),
('I0602125709', '978-0316412001', 1),
('I0602011742', '978-4048661690', 1),
('I0602012045', '978-1101947883', 2),
('I0602013325', '978-0735213616', 1),
('I0609054559', '978-1975399368', 1),
('I0609055138', '978-0735213616', 1),
('I0609055138', '978-1975399368', 1),
('I0609062304', '978-0553380163', 1),
('I0630053611', '978-1975399368', 1);

-- --------------------------------------------------------

--
-- Table structure for table `invoice`
--

CREATE TABLE `invoice` (
  `idinvoice` varchar(15) NOT NULL,
  `order_user` varchar(15) NOT NULL,
  `shipping_add` text NOT NULL,
  `orderdate` date NOT NULL,
  `payby` varchar(15) NOT NULL,
  `paid` tinyint(1) NOT NULL,
  `selldate` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `invoice`
--

INSERT INTO `invoice` (`idinvoice`, `order_user`, `shipping_add`, `orderdate`, `payby`, `paid`, `selldate`) VALUES
('I0528124614', 'freirz', 'Indonesia', '2020-05-28', 'BNI Bank', 1, '2020-05-28'),
('I0528125725', 'fikuri', 'California', '2020-05-28', 'BRI Bank', 1, '2020-05-28'),
('I0528014744', 'fikuri', 'California', '2020-05-28', 'BNI Bank', 1, '2020-06-02'),
('I0528035546', 'freirz', 'Indonesia', '2020-05-28', 'BRI Bank', 1, '2020-06-02'),
('I0602125709', 'freirz', 'Indonesia', '2020-06-02', 'BNI Bank', 1, '2020-06-02'),
('I0602011742', 'freirz', 'Indonesia', '2020-06-02', 'BNI Bank', 1, '2020-06-02'),
('I0602012045', 'freirz', 'Indonesia', '2020-06-02', 'BNI Bank', 1, '2020-06-02'),
('I0602013325', 'freirz', 'Semarang', '2020-06-02', 'Gopay', 1, '2020-06-02'),
('I0609054559', 'fikuri', 'Jakarta', '2020-06-09', 'Mandiri Bank', 0, '0000-00-00'),
('I0609055138', 'fikuri', 'California', '2020-06-09', 'BNI Bank', 1, '2020-06-09'),
('I0609062304', 'fikuri', 'Jakarta', '2020-06-09', 'Mandiri Bank', 0, '0000-00-00'),
('I0630053611', 'fikuri', 'Jalan Anggrek, Jakarta', '2020-06-30', 'BNI Bank', 0, '0000-00-00');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `username` varchar(20) NOT NULL,
  `pass` varchar(15) NOT NULL,
  `name` varchar(20) NOT NULL,
  `gender` varchar(10) NOT NULL,
  `dob` date NOT NULL,
  `address` varchar(30) NOT NULL,
  `email` varchar(20) NOT NULL,
  `role` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`username`, `pass`, `name`, `gender`, `dob`, `address`, `email`, `role`) VALUES
('admin', 'admin', 'Administrator', 'Male', '2020-05-26', 'Indonesia', 'feleventen@gmail.com', 1),
('freirz', 'baka', 'Far', 'Male', '2018-04-27', 'Indonesia', 'feleventen@gmail.com', 2),
('fikuri', 'fiku', 'Fikuri', 'Male', '2000-11-11', 'California', 'fikuri@gmail.com', 2);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
